dist: xenial
language: cpp
compiler: gcc
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq cmake gcc g++ libssl-dev libboost-all-dev
- sh setup_linux.sh
before_script:
- mkdir build
- cd build
- cmake ..
script: make
notifications:
  slack:
    secure: tktQheHzo6D+JHH9mFbrb3bCIFbRnM7PKW4IyB4AW3BZ8cz+PTzH4iLmHvZklEOd4E3GTRJCvhd5mXx4RalNBsrqdUCxTaetqW8EqmvyRxdgf28KhzsrPzJCCmN97SqcCWDOB+KGpoPyDDft8l9voq4mwKsegUSOLtrexpfXz3fSfgt+M5kzkHDlNIOJCq63Q/eaSwNUWawpy2Pv6I9Khh2FDSZtQjh+1sJFmCpjcWBQ2XOfepy+4RhroDozBmk70aSmCP8EWofokflCYZwONJQCYX4gzsFFAM5a9g1HKW+nxWru3nXw2FrBjYom4lN5bfRl2yZ7BOSPP4J0lkpKBuyg5pGg0HwhzlKaKPcwGJ7OaLsLPMXLcEixwnsOtlYux7XQjjIGXrueULYaLOqBUxB+Y13xOJkDn7uP05XrZBCvs/x52Ep59eqleG/PUCtKJoBeC4cY0/2LTio0gtiFwd6Fbx7oj0dr0zNuLCV7+E4ms96XNVAISBCNMzLU+ZqqhdzpEd7jNGevHz19FHXdWfx2TffzpHIx4lpD7IAXIds+bIWb86/JcOVq3wJ+s+WFVSMIW70G/Z+Actb594ey/pJsYUXA3L/AD5DptOUxyuydnDjiCrp/REfRGzc6Wtc9H2MR0kwOsn4URZDBpCQc+GTMq9/5VqXPmPsa5pl6YSU=
